"""Add email verification fields

Revision ID: 002_email_verification
Revises: 001_initial_migration
Create Date: 2025-12-25

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '002_email_verification'
down_revision = '001_initial_migration'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic ###
    op.add_column('users', sa.Column('email_verified', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('verification_code', sa.String(length=6), nullable=True))
    op.add_column('users', sa.Column('verification_code_expires', sa.DateTime(), nullable=True))
    
    # Установить всем существующим пользователям email_verified = True
    op.execute('UPDATE users SET email_verified = TRUE WHERE email_verified IS NULL')
    
    # Теперь делаем поле NOT NULL
    op.alter_column('users', 'email_verified', nullable=False, server_default='false')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic ###
    op.drop_column('users', 'verification_code_expires')
    op.drop_column('users', 'verification_code')
    op.drop_column('users', 'email_verified')
    # ### end Alembic commands ###

